services:
  web_docker_api:
    container_name: web_docker_api
    restart: always
    image: samandardeveloper19/web_docker_api
    ports:
      - "7001:7001"
    depends_on:
      - web_docker_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:7001
      - ConnectionStrings__DefaultConnection=Host=web_docker_db;Port=5432;Database=WebApiDockerDb;Username=postgres;Password=231020044 
    networks:
      - dev-network

  web_docker_db:
    image: postgres
    container_name: web_docker_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=231020044
      - POSTGRES_DB=WebApiDockerDb
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  postgresql-data: